version: '3.1'
services:

  db:
    image: postgres
    restart: always
    ports:
      - "5430:5432"  # host_port:container_port
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db